# Generated by Django 4.2 on 2025-05-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0002_section_compyuter_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='historicalcompyuter',
            name='bg_image',
        ),
        migrations.AlterField(
            model_name='compyuter',
            name='internet',
            field=models.BooleanField(blank=True, default=False, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='historicalcompyuter',
            name='internet',
            field=models.BooleanField(blank=True, default=False, verbose_name='Интернет'),
        ),
    ]
